stages:
  - lint
  - test

flake8:
  image: python:3.9
  stage: lint
  script:
    - pip install tox
    - tox -e flake8

shellcheck:
  image: quay.io/mbukatov/mbukatov-fedora-shellcheck
  stage: lint
  script:
    - shellcheck ocp_network_split/network-split.sh

py37:
  image: python:3.7
  stage: test
  script:
    - pip install tox
    - tox -e py37

py39:
  image: python:3.9
  stage: test
  script:
    - pip install tox
    - tox -e py39
