stages:
  - lint
  - test
  - docs

flake8:
  image: python:3.9
  stage: lint
  script:
    - pip install tox
    - tox -e flake8

shellcheck:
  image: quay.io/mbukatov/mbukatov-fedora-shellcheck
  stage: lint
  script:
    - shellcheck ocpnetsplit/network-split.sh

py37:
  image: python:3.7
  stage: test
  script:
    - pip install tox
    - tox -e py37

py39:
  image: python:3.9
  stage: test
  script:
    - pip install tox
    - tox -e py39

pages:
  image: python:3.9
  stage: docs
  script:
    - pip install sphinx
    - pip install .
    - cd docs
    - sphinx-build -M html . _build
    - mv _build/html ../public
  artifacts:
    paths:
      - public
  only:
    - main
