stages:
  - test

py37:
  image: python:3.7
  stage: test
  script:
    - pip install tox
    - tox -e py37

py39:
  image: python:3.9
  stage: test
  script:
    - pip install tox
    - tox -e py39

flake8:
  image: python:3.9
  stage: test
  script:
    - pip install tox
    - tox -e flake8
