stages:
  - lint
  - test
  - docs

flake8:
  image: python:3.11
  stage: lint
  script:
    - pip install tox
    - tox -e flake8

shellcheck:
  image: quay.io/mbukatov/mbukatov-fedora-shellcheck
  stage: lint
  script:
    - shellcheck ocpnetsplit/*.sh

py38:
  image: python:3.8
  stage: test
  script:
    - pip install tox
    - tox -e py38

py311:
  image: python:3.11
  stage: test
  script:
    - pip install tox
    - tox -e py311

pages:
  image: python:3.11
  stage: docs
  script:
    - pip install sphinx
    - pip install .
    - cd docs
    - sphinx-build -M html . _build
    - mv _build/html ../public
  artifacts:
    paths:
      - public
  only:
    - main
