---
- name: core netsplit setup
  hosts: all
  remote_user: root
  tags:
    - netsplit
  handlers:
    - name: daemon-reload
      ansible.builtin.systemd:
        daemon_reload: true
  tasks:

    - name: Check that env_file is specified
      assert:
        that:
          - env_file is defined
        fail_msg: "you need specify env_file genered by ocp-network-split-mutisetup tool"

    - name: Install dependencies for netsplit setup
      dnf:
        name: iptables
        state: present

    - name: Copy network-split.env file
      copy:
        src: "{{ env_file }}"
        dest: "/etc/network-split.env"
        owner: root
        group: root
      tags:
      - env-file

    - name: Copy netsplit scripts
      copy:
        src: "ocpnetsplit/{{ item }}"
        dest: "/etc/{{ item }}"
        owner: root
        group: root
        mode: 0544
      with_items:
      - network-zone.sh
      - network-split.sh

    - name: Copy netsplit unit files
      copy:
        src: "ocpnetsplit/systemd/{{ item }}"
        dest: "/etc/systemd/system/{{ item }}"
        owner: root
        group: root
      with_items:
      - network-split-ab-ac-setup@.timer
      - network-split-ab-bc-setup@.timer
      - network-split-ab-setup@.timer
      - network-split-ax-bx-cx-setup@.timer
      - network-split-ax-setup@.timer
      - network-split-bc-setup@.timer
      - network-split@.service
      - network-split-teardown.service
      - network-split-teardown@.timer
      notify:
      - daemon-reload
